nelmio_api_doc:
    documentation:
        info:
            title: PunkAPI - DDD
            description: Beers finder!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$)(?!/doc.json) # Accepts routes under /api except /api/doc and /api/doc.json
